
BUILD_NUMBER_OSX = "16156"
BUILD_NUMBER_WIN = "6016"
VERSION_NUMBER = "600"

OS_WINDOWS = "1"
OS_MACOSX = "2"

SCALE_FIT = "0"
SCALE_FILL = "1"
SCALE_STRETCH = "3"

ALIGN_TOP_LEFT = "0"
ALIGN_TOP_CENTER = "1"
ALIGN_TOP_RIGHT = "2"
ALIGN_MIDDLE_LEFT = "3"
ALIGN_CENTER = "4"
ALIGN_MIDDLE_RIGHT = "5"
ALIGN_BOTTOM_LEFT = "6"
ALIGN_BOTTOM_CENTER = "7"
ALIGN_BOTTOM_RIGHT = "8"

TEXT_ALIGN_MIDDLE = "0"
TEXT_ALIGN_TOP = "1"
TEXT_ALIGN_BOTTOM = "2"

REVEAL_NONE = "0"
REVEAL_BULLET_LIST = "1"
REVEAL_BLANK = "2"
PLAY_STOP = "0"
PLAY_LOOP = "1"
